# Generated by Django 2.2.4 on 2022-06-16 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('website_id', models.CharField(max_length=50)),
                ('slider_img1', models.ImageField(blank=True, upload_to='')),
                ('slider_txt1', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('slider_img2', models.ImageField(blank=True, upload_to='')),
                ('slider_txt2', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('slider_img3', models.ImageField(blank=True, upload_to='')),
                ('slider_txt3', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('cv_file', models.ImageField(blank=True, upload_to='')),
                ('about_img', models.ImageField(blank=True, upload_to='')),
                ('about_txt', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_user_id', to='backend_access.User')),
            ],
        ),
        migrations.CreateModel(
            name='Rules_cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rules_id', models.CharField(max_length=50)),
                ('preference', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('conditions', models.TextField(blank=True, validators=[django.core.validators.RegexValidator])),
                ('authorised_by', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_user_id', to='backend_access.User')),
            ],
        ),
    ]
