# Generated by Django 2.2.4 on 2022-06-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('familiar_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_person_no', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar_user_id', to='backend_access.User')),
            ],
        ),
    ]
