# Generated by Django 2.2.4 on 2022-06-16 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('field_id', models.CharField(max_length=50)),
                ('title', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator])),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_field_user_id', to='backend_access.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('income_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('description', models.TextField(blank=True)),
                ('earn_by', models.CharField(max_length=250)),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_field_id', to='additional_income.Field_cl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_user_id', to='backend_access.User')),
            ],
        ),
    ]
