# Generated by Django 2.2.4 on 2022-06-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('metting_id', models.CharField(max_length=50)),
                ('metting_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metting_user_id', to='backend_access.User')),
            ],
        ),
    ]
