# Generated by Django 2.2.4 on 2022-06-16 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator])),
                ('contact_no', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('member_type', models.CharField(default='none', max_length=50)),
                ('shift', models.CharField(max_length=150)),
                ('designation', models.SlugField(max_length=155, validators=[django.core.validators.RegexValidator])),
                ('salary', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('leaving_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user_id', to='backend_access.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('trash', models.BooleanField(default=False)),
                ('member_id', models.ManyToManyField(blank=True, related_name='team_member_ids', to='team.Member_cl')),
                ('team_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_head_id', to='team.Member_cl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user_id', to='backend_access.User')),
            ],
        ),
    ]
